version: "3.9"

services:
  api:
    container_name: env-fastapi
    hostname: env-fastapi
    restart: always
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    command: .venv/bin/gunicorn -w 1 -k uvicorn.workers.UvicornWorker --capture-output --log-level warning --access-logfile - --bind :80 app.main:app
    expose:
      - 80
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.env-fastapi.entrypoints=web
      - traefik.http.routers.env-fastapi.rule=Host(`env-fastapi.localhost`)

networks:
  web:
    name: docker-mgr_web
    external: true
