version: "3.9"

services:
  api:
    container_name: fastapi
    hostname: fastapi
    restart: always
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    command: .venv/bin/gunicorn -w 1 -k uvicorn.workers.UvicornWorker --capture-output --log-level warning --access-logfile - --bind :80 --reload app.main:app
    expose:
      - 80
    volumes:
      - ./api/app/app:/app/app
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.env-fastapi.entrypoints=web
      - traefik.http.routers.env-fastapi.rule=Host(`env-fastapi.localhost`)

  db:
    container_name: postgres
    hostname: postgres
    restart: always
    tty: true
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 9000:5432
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi

networks:
  web:
    name: docker-mgr_web
    external: true
